name: check_ongkir_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dropdown_search: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.4
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true
